global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'big-market-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'big-market-app-01:8091'
          - 'big-market-app-02:8092'
        labels:
          app: 'big-market-app'
